source "http://rubygems.org"

gem "sinatra"
gem "slim"
gem "sinatra-activerecord"
gem "sinatra-sse"
gem "sinatra-contrib"
gem "bcrypt"
gem "sqlite3"
gem "rack", "1.5.2"
gem "dberkom-sinatra-prawn"
gem "prawn"
gem "prawn-table"